# nanodet-EfficientNet-Lite0_320
# COCO mAP(0.5:0.95) = 0.247
#             AP_50  = 0.404
#             AP_75  = 0.250
#           AP_small = 0.079
#               AP_m = 0.243
#               AP_l = 0.406
save_dir: workspace/efficient0_320
model:
  arch:
    name: OneStageDetector
    backbone:
      name: EfficientNetLite
      model_name: efficientnet_lite0
      out_stages: [2,4,6]
      activation: ReLU6
    fpn:
      name: PAN
      in_channels: [40, 112, 320]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 7
      input_channel: 96
      feat_channels: 96
      activation: ReLU6
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
data:
  train:
    name: CocoDataset
    img_path: /home/nthere/2021/fractionfish/data/coco/images/
    ann_path: /home/nthere/2021/fractionfish/data/coco/train.json
    input_size: [160,320] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[127.0, 127.0, 127.0], [128.0, 128.0, 128.0]]
  val:
    name: CocoDataset
    img_path: /home/nthere/2021/fractionfish/data/coco/images/
    ann_path: /home/nthere/2021/fractionfish/data/coco/val.json
    input_size: [160,320] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[127.0, 127.0, 127.0], [128.0, 128.0, 128.0]]
device:
  gpu_ids: [0]
  workers_per_gpu: 12
  batchsize_per_gpu: 150
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: SGD
    lr: 0.15
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 500
    ratio: 0.01
  total_epochs: 190
  lr_schedule:
    name: MultiStepLR
    milestones: [140,170,180,185]
    gamma: 0.1
  val_intervals: 1
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10

class_names: ['whole', 'half', 'third', 'fourth', 'sixth', 'eighth',
'twelvth']
